### ISSUE TITLE
[feature] Tag Colors

### ISSUE THREAD

**Issue by goldbattle** [sharelatex/tags-sharelatex#1]
It would be nice to assign tags a color, so that they can be easily distinguished at a glance. Could be easy as setting the `color:#FF4136` on the favicon. Just offering the [basic html variations](http://clrs.cc/) would be nice. Thanks!

![image](https://cloud.githubusercontent.com/assets/2222562/16510012/8ac33388-3f10-11e6-91c3-c1fb0371ab9f.png)
![image](https://cloud.githubusercontent.com/assets/2222562/16509982/2cdea388-3f10-11e6-8e8d-d0187de82ec3.png)

**Comment by robertacucuzza** [comment]
@jdleesmiller can this ticket be closed as we are reviewing all the labels now?

**Comment by jdleesmiller** [comment]
Yes, this is now done.

![image](https://user-images.githubusercontent.com/160829/61045786-7487e200-a3d3-11e9-9c36-db30d889a0db.png)
